//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EraserBotFrontend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EraserBotFrontend.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bots.cfg is empty. No bots are available for play..
        /// </summary>
        internal static string BotsFileEmpty {
            get {
                return ResourceManager.GetString("BotsFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        internal static string BotsTabText {
            get {
                return ResourceManager.GetString("BotsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the applications&apos; settings. Be sure to select the paths for Quake II and Eraser Bot by clicking Tools -&gt; Configuration..
        /// </summary>
        internal static string ConfigurationFileError {
            get {
                return ResourceManager.GetString("ConfigurationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation needed.
        /// </summary>
        internal static string ConfirmationNeeded {
            get {
                return ResourceManager.GetString("ConfirmationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops.
        /// </summary>
        internal static string EBFInitErrorTitle {
            get {
                return ResourceManager.GetString("EBFInitErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialise EBF.
        /// </summary>
        internal static string FailedtoInitEBF {
            get {
                return ResourceManager.GetString("FailedtoInitEBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paths for Quake II or Eraser bot haven&apos;t been set. In the next dialog, please show where both items are located..
        /// </summary>
        internal static string FirstRunMessage {
            get {
                return ResourceManager.GetString("FirstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration needed.
        /// </summary>
        internal static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory doesn&apos;t contain a valid Eraser installation. Skipping..
        /// </summary>
        internal static string InvalidEraserInstallation {
            get {
                return ResourceManager.GetString("InvalidEraserInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory doesn&apos;t contain a valid Quake II installation. Skipping..
        /// </summary>
        internal static string InvalidQuake2Installation {
            get {
                return ResourceManager.GetString("InvalidQuake2Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialise Irrlicht. MD2 viewing will be unavailable..
        /// </summary>
        internal static string IrrlichtInitializationErrorMsg {
            get {
                return ResourceManager.GetString("IrrlichtInitializationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paths for Quake II and Eraser Bot have not been set. Set the paths by clicking Tools -&gt; Paths and then try again..
        /// </summary>
        internal static string LaunchPathsNotSet {
            get {
                return ResourceManager.GetString("LaunchPathsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Settings.
        /// </summary>
        internal static string MatchSettingsTabText {
            get {
                return ResourceManager.GetString("MatchSettingsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bots have been selected. Continue?.
        /// </summary>
        internal static string NoBotsSelected {
            get {
                return ResourceManager.GetString("NoBotsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps have been selected, choose one and try again..
        /// </summary>
        internal static string NoMapsSelected {
            get {
                return ResourceManager.GetString("NoMapsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps selected.
        /// </summary>
        internal static string NoMapsSelectedTitle {
            get {
                return ResourceManager.GetString("NoMapsSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoMatchTypeSelected {
            get {
                return ResourceManager.GetString("NoMatchTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opposing teams have been selected..
        /// </summary>
        internal static string NoOpposingTeams {
            get {
                return ResourceManager.GetString("NoOpposingTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths have been reset..
        /// </summary>
        internal static string PathsReset {
            get {
                return ResourceManager.GetString("PathsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t joined a team..
        /// </summary>
        internal static string PlayerHasntJoinedATeam {
            get {
                return ResourceManager.GetString("PlayerHasntJoinedATeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team and the opposing team are the same. Try again, spud..
        /// </summary>
        internal static string PlayerOppositionTeamsSame {
            get {
                return ResourceManager.GetString("PlayerOppositionTeamsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerTabText {
            get {
                return ResourceManager.GetString("PlayerTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string TeamTabText {
            get {
                return ResourceManager.GetString("TeamTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue.
        /// </summary>
        internal static string UnableToContinue {
            get {
                return ResourceManager.GetString("UnableToContinue", resourceCulture);
            }
        }
    }
}
